name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - '**'
    paths:
      - 'src/**'
      - '.github/workflows/ci.yml'

permissions:
  contents: read

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    strategy:
      fail-fast: false
      matrix:
        dotnet: ['9.0.x']

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET ${{ matrix.dotnet }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet }}

      - name: Cache NuGet
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.sln', '**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Restore
        run: dotnet restore ./src

      - name: Build (Release, no restore)
        run: dotnet build ./src --configuration Release --no-restore

      - name: Test (com cobertura)
        run: |
          dotnet test ./src \
            --configuration Release \
            --no-build \
            --collect:"XPlat Code Coverage" \
            --logger "trx;LogFileName=test_results.trx"
